
CXX_FLAGS = -lGL -lglut

all: sampleview samplegenerate
sampleview: sampleview.cpp
	g++ -g -o sampleview sampleview.cpp $(CXX_FLAGS)

samplegenerate: samplegenerate.cpp
	g++ -g -o samplegenerate samplegenerate.cpp
